grounding_dino:
  config_file: "/home/parksanghyun/gsam_ws/external/GroundingDINO/groundingdino/config/GroundingDINO_SwinT_OGC.py"
  checkpoint: "/home/parksanghyun/gsam_ws/models/groundingdino_swint_ogc.pth"
  box_threshold: 0.35
  text_threshold: 0.25
  device: "cpu"

sam:
  model_type: "vit_h"
  checkpoint: "/home/parksanghyun/gsam_ws/models/sam_vit_h_4b8939.pth"
  device: "cpu"
