grounding_dino:
  config_file: "${GSAM_WS}/external/GroundingDINO/groundingdino/config/GroundingDINO_SwinT_OGC.py"
  checkpoint: "${GSAM_WS}/models/groundingdino_swint_ogc.pth"
  box_threshold: 0.35
  text_threshold: 0.25
  device: "cpu"

sam:
  model_type: "vit_b"
  checkpoint: "${GSAM_WS}/models/sam_vit_b_01ec64.pth"
  device: "cpu"
